apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ge-postgres.fullname" . }}
  labels:
    {{- include "ge-postgres.labels" . | nindent 4 }} 
spec:
  finelizer: ""
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath  # Or the name of your StorageClass
  resources:
    requests:
      storage: 10Gi